apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::352105258251:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::352105258251:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-16U4IO78VDAP0
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-14T07:16:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "31607"
  uid: a731c460-2a67-44cc-98da-4e05fae14bc7
